name: blast_rbh
owner: peterjc
homepage_url: https://github.com/peterjc/galaxy_blast/tools/blast_rbh
remote_repository_url: https://github.com/peterjc/galaxy_blast/tools/blast_rbh
description: BLAST Reciprocal Best Hits (RBH) from two FASTA files
long_description: |
  Builds BLAST databases and runs reciprocal searches, filters them,
  and then identifies and reports any reciprocal best hits (RBH).
categories:
- Fasta Manipulation
- Sequence Analysis
type: unrestricted
